spring:
  datasource:
    password: letmein
    url: jdbc:postgresql://localhost:5432/serverdb
    username: william
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
